---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.55.55"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[nexus_wrapper::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
